pool:
  vmImage: 'windows-latest'

variables:
  solution: 'DnDGen.TreasureGen.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- checkout: self
  displayName: 'Checkout Code'
  persistCredentials: true
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: './DnDGen.TreasureGen/DnDGen.TreasureGen.csproj'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Unit Tests
  inputs:
    command: test
    projects: './DnDGen.TreasureGen.Tests.Unit/DnDGen.TreasureGen.Tests.Unit.csproj'
    arguments: '-v normal --collect "Code Coverage"'
- task: DotNetCoreCLI@2
  displayName: IoC Tests
  inputs:
    command: test
    projects: './DnDGen.TreasureGen.Tests.Integration.IoC/DnDGen.TreasureGen.Tests.Integration.IoC.csproj'
    arguments: '-v normal --collect "Code Coverage"'
- task: DotNetCoreCLI@2
  displayName: Table Tests
  inputs:
    command: test
    projects: './DnDGen.TreasureGen.Tests.Integration.Tables/DnDGen.TreasureGen.Tests.Integration.Tables.csproj'
    arguments: '-v normal --collect "Code Coverage"'
- task: DotNetCoreCLI@2
  displayName: Integration Tests
  inputs:
    command: test
    projects: './DnDGen.TreasureGen.Tests.Integration/DnDGen.TreasureGen.Tests.Integration.csproj'
    arguments: '-v normal --collect "Code Coverage"'
- task: DotNetCoreCLI@2
  displayName: Stress Tests
  inputs:
    command: test
    projects: './DnDGen.TreasureGen.Tests.Integration.Stress/DnDGen.TreasureGen.Tests.Integration.Stress.csproj'
    arguments: '-v normal --configuration Stress --collect "Code Coverage"'

- task: PowerShell@2
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: 'Get Project Version'
  inputs:
    targetType: 'inline'
    script: |
         $xml = [Xml] (Get-Content ./DnDGen.TreasureGen/DnDGen.TreasureGen.csproj)
         $version = $xml.Project.PropertyGroup.Version
         echo $version
         echo "##vso[task.setvariable variable=version]$version"
    
- script: |
     echo "Tagging with version $(version)"
     git tag $(version)
     git push origin $(version)
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: 'Tag Version'
  workingDirectory: $(Build.SourcesDirectory)

- task: PublishBuildArtifacts@1
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: Publish Artifacts
  inputs:
    pathtoPublish: './DnDGen.TreasureGen/bin/Release' 
    artifactName: 'dndgen-treasuregen'
